# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-08-20 09:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0005_auto_20180809_1655'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='teacher_tell',
            field=models.CharField(default='', max_length=300, verbose_name='讲师提示'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='youneed_know',
            field=models.CharField(default='', max_length=300, verbose_name='课程须知'),
        ),
    ]
