# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-08-15 16:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_course_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='url',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='视频链接'),
        ),
    ]
