# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-08-16 10:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_video_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='hot',
            field=models.CharField(default=0, max_length=20, verbose_name='课程热度'),
        ),
    ]
