# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-08-16 14:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_course_hot'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_type',
            field=models.CharField(default='', max_length=30, verbose_name='课程类别'),
        ),
    ]
